name: Robot Framework Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Firefox + GeckoDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox xvfb
          GECKO_VER=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep "tag_name" | cut -d '"' -f 4)
          wget https://github.com/mozilla/geckodriver/releases/download/$GECKO_VER/geckodriver-$GECKO_VER-linux64.tar.gz
          tar -xvzf geckodriver-*-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install --upgrade robotframework-seleniumlibrary
          pip install git+https://github.com/robotframework/SeleniumLibrary.git
          pip install webdriver-manager

      - name: Run Robot Framework Tests
        run: |
          if ! robot --outputdir results --exclude skip tests/; then
              echo "Robot Framework tests failed. Rerunning failed tests..."
              if [ -f results/output.xml ]; then
                  robot --rerunfailed results/output.xml --outputdir results_rerun tests/ || true
                  if [ -f results_rerun/output.xml ]; then
                      rebot --output results/output.xml --log results/log.html --report results/report.html --merge results/output.xml results_rerun/output.xml
                  else
                      echo "No output.xml file found from rerun. Skipping merge."
                  fi
              else
                  echo "No output.xml file found. Cannot rerun failed tests."
              fi
          fi

          echo "Script execution completed"
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-results
          path: results
